### ISSUE TITLE
Need some help in creating, the about page.

### ISSUE THREAD

**Issue by preyashyadav** [A-116-Coders/Design-Challenge--2#1]

**Comment by AditiBendre** [comment]
Hii
What should the about page contain and how do you want it?

**Comment by Dishagupta224** [comment]
heyy
I can work on it, please assign it to me

**Comment by preyashyadav** [comment]
![image](https://user-images.githubusercontent.com/73031725/194752840-ca60a475-f504-4f6a-a280-83604d7ff15a.png)
The page should look some what like this!

**Comment by Dishagupta224** [comment]
Yeah..I can make it..

**Comment by preyashyadav** [comment]
Alright!

**Comment by AditiBendre** [comment]
I can do it

**Comment by preyashyadav** [comment]
@AditiBendre you can work on the bottom part:

![image](https://user-images.githubusercontent.com/73031725/194753180-9afd165c-b7c4-40e2-b259-f24fb43e4e6c.png)

This looks little clumsy and hard to read, please try to make changes to the CSS for this section

**Comment by AditiBendre** [comment]
Ok. Will send a PR today.

**Comment by preyashyadav** [comment]
Sure!
